### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Lapsus** [MarvinWank/vog#5]
Hallo Marvin,

zu erst mal ein frohes neues Jahr. Ich schreibe mal auf deutsch, das ist hoffentlich für dich ok.

Ich finde dein Tool super. Genau so etwas suche ich schon seit einiger Zeit. Ich hätte ein paar Vorschläge und Ideen die ich gern mit dir diskutieren möchte. Ich kann dich auch bei der Umsetzung dieser Ideen unterstützen. Hast du Interesse, bzw. möchtest du Unterstützung?

Viele Grüße aus Freiburg
Dirk

**Comment by MarvinWank** [comment]
Hi Dirk,

ebenso frohes neues :) Natürlich ist Deutsch in Ordnung für mich.

Ich freue mich, dass dir mein Tool gefällt und würde mich sehr über Anregungen und Unterstützung freuen. Schreib mir doch gern eine E-Mail an marvin.wank@outlook.de
